version: '3.7'
services:
  zookeeper:
   image: confluentinc/cp-zookeeper:5.2.2
   container_name: "zookeeper"
   ports:
    -"2181:2181"
   restart: unless-stopped
   environment:
    ZOOKEEPER_CLIENT_PORT: "2181"

  kafka:
    depends_on:
      - "stedi"
    image: confluentinc/cp-kafka:5.5.1
    container_name: kafka
    expose:
      - "19092"
    environment:
      - KAFKA_BROKER_ID: "0"
      - KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2180"
      - KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:19092"
      - KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT"
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    restart: unless-stopped

  redis:
    image: redis:6.0.6
    container_name: "redis"
    restart: unless_stopped
    expose:
      - "6379"  #hope this works well

  stedi:
    image: scmurdock/stedi
    ports: 
    - "4567:4567"  
    enviroment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: 0
      KAFKA_BROKER: "kafka:19092"
      KAFKA_RISK_TOPIC: "customer-risk-topic"
    depends_on:
    - "redis"
    - "kafka"
