version: '3.7'
services:
  zookeeper:

  kafka:

  redis:

  stedi:
    image: scmurdock/stedi
    ports: 
    - "4567:4567"  
    enviroment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: 0
      KAFKA_BROKER: "kafka:19092"
      KAFKA_RISK_TOPIC: "customer-risk-topic"
    depends_on:
    - "redis"