version: '3.7'
services:
  zookeeper:

  kafka:
    depends_on:
      - "stedi"
    image: confluentinc/cp-kafka:5.5.1
    container_name: kafka
    restart: unless-stopped
    expose:
      - "19092"
    environment:

  redis:

  stedi: